name: DevSecOps Tamim CI Pipeline


on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Lint YAML files
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
          echo -e "extends: default\nrules:\n  line-length: disable\n  document-start: disable" > .yamllint
          yamllint k8s.yaml


      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true


      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
          docker build -t devsecops-flask-api:latest .

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'


      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-flask-api:latest'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'

      - name: Run Conftest to check Kubernetes security policies
        uses: instrumenta/conftest-action@master
        with:
          files: k8s.yaml
          policy: policy/deployment.rego